# Используем базовый образ Nginx
FROM nginx:alpine

# Копируем статические файлы фронтенда
COPY templates /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]